# Generated by Django 4.2.8 on 2023-12-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_delete_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='content',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
    ]
