# Generated by Django 4.2.8 on 2023-12-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_content_profile_score_remove_profile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='bestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
            ],
        ),
    ]
